pipeline:
  identifier: Build_geanenova_node_ztools_1736727857042
  name: Build node-ztools
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash && export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && nvm install node && nvm use node && git clone https://github.com/geanenova/node-ztools && cd node-ztools && node app.js
                  timeout: 1w
  properties:
    ci:
      codebase:
        repoName: tgest
        build: <+input>
